println "[tagit-sonar] Applying TagitCore v7.5.1 Sonar plug-ins, configurations and dependencies for Java applications"

def removeSnapshot(String version) {
    if (version.trim().endsWith("-SNAPSHOT")) {
        return version.trim().substring(0, version.trim().length() - "-SNAPSHOT".length())
    }
    return version
}

// Ensure JUnit Tests still run without Jacoco or Sonar
tasks.withType(Test).configureEach {
    // tell Gradle to use JUnit Platform (JUnit 5)
    useJUnitPlatform()

    ignoreFailures = true

	// Ensure JUnit Tests does not run by default, but must be included explicitly, i.e. `gradlew test`
    onlyIf { gradle.startParameter.taskNames.contains('test') }
}

if (project.tasks.findByName('jacocoTestReport')) {
    println "[jacoco] Jacoco plugin found. Performing Jacoco auto-configuration."

    jacoco {
        toolVersion = "0.8.13"
        // reportsDirectory = layout.buildDirectory.dir('customJacocoReportDir') // use defaults
    }

    tasks.withType(Test).configureEach {
        finalizedBy("jacocoTestReport")
    }

    tasks.named("jacocoTestReport", JacocoReport) {
        dependsOn("test")
        mustRunAfter("test")
        // Always run, even if no test .exec exists
        onlyIf { true }

        reports {
            xml.required.set(true) // required by SonarQube Jacoco integration
            csv.required.set(false)
            html.required.set(true)
            html.outputLocation.set(layout.buildDirectory.dir("jacocoHtml"))
        }
    }

    // Ensure coverage is part of the "check" lifecycle
    tasks.named("check") {
        dependsOn("jacocoTestReport")
    }
    
    // Root-level task to run all jacocoTestReports in subprojects
	if (project == rootProject) {
	  tasks.register("jacocoRootReport", DefaultTask) {
	    group       = "verification"
	    description = "Aggregate JaCoCo from all subprojects"
	
	    dependsOn subprojects
	      .collect { it.tasks.findByName("jacocoTestReport") }
	      .findAll { it != null }
	
	    doFirst {
	      // this block only runs if jacocoRootReport itself is running
	      def xmls = subprojects.collect { sub ->
	        file("${sub.buildDir}/reports/jacoco/test/jacocoTestReport.xml")
	      }.findAll { it.exists() }
	
	      if (xmls) {
	        println "[jacocoRootReport] Aggregating XMLs: $xmls"
	        project.sonarqube.properties {
	          property "sonar.coverage.jacoco.xmlReportPaths", xmls*.absolutePath.join(",")
	        }
	      } else {
	        println "[jacocoRootReport] No Jacoco XMLs to aggregate or no Gradle subprojects " + subprojects + " defined."
	      }
	    }
	  }
	}    
    
    jacocoTestCoverageVerification {
        violationRules {
            rule {
                limit {
                    minimum = 0.0
                }
            }
        }
    }

} else {
    println "[jacoco] Jacoco task or plugin is not found. Skipping Jacoco auto-configuration."
}

if (project.tasks.findByName('sonar')) {
    println "[sonar] SonarQube plugin found. Performing SonarQube auto-configuration."
    sonar {
        properties {
            def mobeixPackages = ["com.mobeix", "com.tagit.mobeix", "com.tagit.commons"]
            def mcbPackages = ["com.tagit.mcb", "com.tagit.dcb"]
            def mrbPackages = ["com.tagit.mrb", "com.tagit.drb"]
            def mfbPackages = ["com.tagit.mfb"]
            def mdbPackages = ["com.tagit.digital", "com.tagit.mdb"]
            def tagitPackages = ["com.tagit"]

            if ( mobeixPackages.any { pckg -> group.startsWith(pckg) } ) {
                println "[sonarqube] Using Mobeix Product SonarQube server for '${group}' package."
                property "sonar.host.url", "https://mobeix-sonarqube.tagitmobile.com"
                property "sonar.login", "squ_c995a5fcf7cfe1f39e449d96678c0fef5e9d517d"
            } else if ( mcbPackages.any { pckg -> group.startsWith(pckg) } ) {
                println "[sonarqube] Using MCB Product SonarQube server for '${group}' package."
                property "sonar.host.url", "https://mcb-sonarqube.tagitmobile.com"
                property "sonar.login", "squ_b9aefc5710769265d27ded03d8b3bed5194f396f"
            } else if ( mrbPackages.any { pckg -> group.startsWith(pckg) } ) {
                println "[sonarqube] Using MRB Product SonarQube server for '${group}' package."
                property "sonar.host.url", "https://mrb-sonarqube.tagitmobile.com"
                property "sonar.login", "squ_8a25ab9fa5cb7b7e4f1f203fc4a215e3f3317c6c"
            } else if ( mfbPackages.any { pckg -> group.startsWith(pckg) } ) {
                println "[sonarqube] Using MFB Product SonarQube server for '${group}' package."
                property "sonar.host.url", "https://mfb-sonarqube.tagitmobile.com"
                property "sonar.login", "squ_7b80e965d10022e20af899f8177ef9ad64a436ee"
            } else if ( mdbPackages.any { pckg -> group.startsWith(pckg) } ) {
                println "[sonarqube] Using MDB Product SonarQube server for '${group}' package."
                property "sonar.host.url", "https://mdb-sonarqube.tagitmobile.com"
                property "sonar.login", "squ_27d52517acaa070ac90fcd690d02b02a591e1671"
            } else if ( tagitPackages.any { pckg -> group.startsWith(pckg) } ) {
                println "[sonarqube] Using Tagit SonarQube server for '${group}' package."
                property "sonar.host.url", "https://sonarqube.tagitmobile.com"
                property "sonar.login", "squ_f4caa57be81d3fc0e599c550e093ba4b657b0df7"
            } else {
                println "[sonarqube] Using Project Services SonarQube server for '${group}' package."
//                property "sonar.host.url", "https://sonarqube-services.tagitmobile.com"
//                property "sonar.login", "01a86c235e09af8e5cee2260718e590295c6a933"        
                property "sonar.host.url", "https://project-sonarqube.tagitmobile.com"
                property "sonar.login", "squ_0a43ac2bd18423b1d32a09b4843cedce28acb6f0"        
            }

            // [rj.added 2024.06.18] follow the https://edocs1.tagitmobile.com/confluence/pages/viewpage.action?spaceKey=PPDG&title=Code+Quality+Guidelines
            property("sonar.projectKey", "${group}:${rootProject.name}${project.path}:${removeSnapshot(project.version)}")
            property("sonar.projectName", "${project.name}-${removeSnapshot(project.version)}")

            property "sonar.sourceEncoding", "UTF-8"
            // property "sonar.sources", "src/main/java" // use defaults
            // property "sonar.tests", "src/test/java" // use defaults
            // property "sonar.java.binaries", "build/classes"  // use defaults
            property "sonar.gradle.skipCompile", "true"

        }
    }

    // ensure Sonar runs only after Jacoco
    if (project.tasks.findByName('jacocoTestReport')) {
        tasks.named("sonar") { 
            dependsOn("check") 
        }
    }

    task printSonarProperties {
		doLast {
			println "[sonarqube] Project Name: " + "${project.tasks['sonarqube'].properties['sonar.projectName'].get()}"
			println "[sonarqube] Project Key: " + "${project.tasks['sonarqube'].properties['sonar.projectKey'].get()}"
		}
	}
	project.tasks["sonar"].dependsOn "printSonarProperties"  
} else {
    println "[sonar] Sonar task or plugin is not found. Skipping Sonar auto-configuration."
}

