println "[tagit-settings] Applying TagitCore v7.5.1 Settings DSL plug-ins"

// How to apply Remote Object Cache
// see https://edocs1.tagitmobile.com/confluence/display/PPDG/Migration+Guide+-+Gradle
buildscript {
	repositories { gradlePluginPortal() }
	dependencies { classpath("com.atkinsondev.object-store-cache:com.atkinsondev.object-store-cache.gradle.plugin:2.1.0") }
}
apply(plugin: "com.atkinsondev.object-store-cache")
//pluginManager.apply("com.atkinsondev.object-store-cache")

boolean isCI = System.getenv("CI") != null

String cacheEndpointUrl = System.getenv("BUILD_CACHE_ENDPOINT_URL") ?: properties['cache_endpoint_url']
String cacheAccessKey = System.getenv("BUILD_CACHE_ACCESS_KEY") ?: properties['cache_access_key']
String cacheSecretKey = System.getenv("BUILD_CACHE_SECRET_KEY") ?: properties['cache_secret_key']

println "[cache] Applying Object Store Gradle Build Cache with CI is '${isCI}' and cache endpoint URL is '${cacheEndpointUrl}'"

def cacheClass = Class.forName("com.atkinsondev.cache.ObjectStoreBuildCache")

buildCache {
    local {
        enabled = !isCI // use local for local development
    }
    remote(cacheClass) {
        endpoint = cacheEndpointUrl
        accessKey = cacheAccessKey
        secretKey = cacheSecretKey
        bucket = 'gradle-build-cache'
        autoCreateBucket = true
        expirationInDays = 10
        push = isCI
    }
}
